export { Nav } from "./nav"
export { Hero } from "./hero"
export { Services } from "./services"
export { WhyUs } from "./why-us"
export { Reviews } from "./reviews"
export { ServiceAreas } from "./service-areas"
export { Contact } from "./contact"
export { Footer } from "./footer"
export { getIcon, ICON_MAP } from "./icon-map"
